BEGIN;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'operator'
        CHECK (role IN ('admin', 'analyst', 'operator')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_code VARCHAR(50),
    name VARCHAR(160) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_customers_external_code UNIQUE (external_code)
);

CREATE TABLE regions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
    name VARCHAR(120) NOT NULL,
    state_code CHAR(2),
    centroid_latitude NUMERIC(9,6)
        CHECK (centroid_latitude IS NULL OR centroid_latitude BETWEEN -90 AND 90),
    centroid_longitude NUMERIC(9,6)
        CHECK (centroid_longitude IS NULL OR centroid_longitude BETWEEN -180 AND 180),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_regions_customer_name UNIQUE (customer_id, name)
);

CREATE TABLE equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
    current_region_id BIGINT REFERENCES regions(id) ON DELETE SET NULL,
    external_code VARCHAR(50) NOT NULL,
    equipment_type VARCHAR(80) NOT NULL,
    manufacturer VARCHAR(80),
    model VARCHAR(100),
    manufacture_year SMALLINT
        CHECK (manufacture_year IS NULL OR manufacture_year BETWEEN 1950 AND 2100),
    weight_tons NUMERIC(8,2) NOT NULL CHECK (weight_tons > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'maintenance', 'inactive')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_equipment_customer_code UNIQUE (customer_id, external_code)
);

CREATE TABLE maintenance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id BIGINT NOT NULL REFERENCES equipment(id) ON DELETE CASCADE,
    performed_at TIMESTAMPTZ NOT NULL,
    maintenance_type VARCHAR(80) NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id BIGINT NOT NULL REFERENCES equipment(id) ON DELETE RESTRICT,
    region_id BIGINT REFERENCES regions(id) ON DELETE SET NULL,
    incident_type VARCHAR(50) NOT NULL,
    severity VARCHAR(20)
        CHECK (severity IS NULL OR severity IN ('low', 'medium', 'high', 'critical')),
    occurred_at TIMESTAMPTZ NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id BIGINT NOT NULL REFERENCES equipment(id) ON DELETE RESTRICT,
    region_id BIGINT NOT NULL REFERENCES regions(id) ON DELETE RESTRICT,
    operator_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,

    -- Business grouping used by dashboard / Sompo user stories.
    operation_category VARCHAR(20) NOT NULL
        CHECK (operation_category IN ('field', 'transport', 'near_water')),

    -- Detailed operational activity used by the ML feature, e.g. plantio,
    -- colheita, pulverizacao, transporte.
    operation_type VARCHAR(50) NOT NULL,

    status VARCHAR(20) NOT NULL DEFAULT 'planned'
        CHECK (status IN ('planned', 'running', 'paused', 'completed', 'cancelled')),
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_operations_dates CHECK (
        ended_at IS NULL OR started_at IS NULL OR ended_at >= started_at
    )
);

CREATE TABLE telemetry_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT NOT NULL REFERENCES operations(id) ON DELETE CASCADE,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    rainfall_mm NUMERIC(8,2) NOT NULL DEFAULT 0 CHECK (rainfall_mm >= 0),
    temperature_c NUMERIC(6,2) NOT NULL CHECK (temperature_c BETWEEN -50 AND 80),
    soil_moisture_pct NUMERIC(6,2) NOT NULL CHECK (soil_moisture_pct BETWEEN 0 AND 100),
    soil_type VARCHAR(40) NOT NULL,
    slope_degrees NUMERIC(6,2) NOT NULL CHECK (slope_degrees BETWEEN 0 AND 90),
    distance_to_water_m NUMERIC(10,2) NOT NULL CHECK (distance_to_water_m >= 0),

    speed_kmh NUMERIC(7,2) CHECK (speed_kmh IS NULL OR speed_kmh >= 0),
    latitude NUMERIC(9,6)
        CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    longitude NUMERIC(9,6)
        CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),

    source VARCHAR(20) NOT NULL DEFAULT 'simulator'
        CHECK (source IN ('simulator', 'device', 'manual', 'import')),
    raw_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE model_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR(100) NOT NULL DEFAULT 'somple-risk-classifier',
    version VARCHAR(40) NOT NULL,
    artifact_uri TEXT NOT NULL,
    artifact_sha256 CHAR(64),
    training_dataset_version VARCHAR(80),
    metrics JSONB NOT NULL DEFAULT '{}'::JSONB,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_model_versions_name_version UNIQUE (model_name, version)
);

CREATE TABLE risk_assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id BIGINT NOT NULL REFERENCES operations(id) ON DELETE RESTRICT,
    telemetry_reading_id BIGINT NOT NULL REFERENCES telemetry_readings(id) ON DELETE RESTRICT,
    model_version_id BIGINT NOT NULL REFERENCES model_versions(id) ON DELETE RESTRICT,

    risk_score SMALLINT NOT NULL CHECK (risk_score BETWEEN 0 AND 100),
    risk_level VARCHAR(20) NOT NULL
        CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),
    confidence NUMERIC(7,6)
        CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),

    -- Immutable snapshot of the exact feature vector sent to the model.
    -- This is the central auditability field for Sprint 3.
    input_snapshot JSONB NOT NULL,
    output_snapshot JSONB NOT NULL DEFAULT '{}'::JSONB,
    explanation_summary TEXT,

    predicted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_risk_assessment_reading_model
        UNIQUE (telemetry_reading_id, model_version_id)
);

CREATE TABLE risk_factors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES risk_assessments(id) ON DELETE CASCADE,
    rank SMALLINT NOT NULL CHECK (rank > 0),
    factor_code VARCHAR(80) NOT NULL,
    factor_label VARCHAR(160) NOT NULL,
    feature_name VARCHAR(80),
    feature_value JSONB,
    importance NUMERIC(9,8) CHECK (importance IS NULL OR importance BETWEEN 0 AND 1),
    direction VARCHAR(10)
        CHECK (direction IS NULL OR direction IN ('increase', 'decrease', 'neutral')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_risk_factors_assessment_rank UNIQUE (assessment_id, rank)
);

CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES risk_assessments(id) ON DELETE CASCADE,
    severity VARCHAR(20) NOT NULL
        CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    status VARCHAR(20) NOT NULL DEFAULT 'open'
        CHECK (status IN ('open', 'acknowledged', 'resolved', 'dismissed')),
    title VARCHAR(160) NOT NULL,
    message TEXT NOT NULL,
    recommendation TEXT,
    acknowledged_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    acknowledged_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_alert_acknowledgement CHECK (
        (status <> 'acknowledged') OR acknowledged_at IS NOT NULL
    )
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    event_type VARCHAR(80) NOT NULL,
    entity_type VARCHAR(80),
    entity_id BIGINT,
    request_id VARCHAR(64),
    endpoint VARCHAR(255),
    http_method VARCHAR(10),
    status_code SMALLINT CHECK (status_code IS NULL OR status_code BETWEEN 100 AND 599),
    ip_address INET,
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Generic updated_at trigger.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_customers_updated_at
BEFORE UPDATE ON customers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_regions_updated_at
BEFORE UPDATE ON regions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_equipment_updated_at
BEFORE UPDATE ON equipment
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;
