-- SOMPLE - Sprint 2
-- Script SQL para persistência dos dados operacionais, variáveis de risco e saídas do modelo.

CREATE TABLE equipamento (
    id_equipamento VARCHAR2(20) PRIMARY KEY,
    tipo VARCHAR2(50) NOT NULL,
    peso_base_t NUMBER(5,2) NOT NULL,
    status VARCHAR2(30) DEFAULT 'ativo' NOT NULL
);

CREATE TABLE leitura_operacional (
    id_registro NUMBER PRIMARY KEY,
    id_equipamento VARCHAR2(20) NOT NULL,
    regiao VARCHAR2(80) NOT NULL,
    chuva_mm NUMBER(6,2) NOT NULL,
    temperatura_c NUMBER(5,2) NOT NULL,
    umidade_solo NUMBER(5,2) NOT NULL,
    tipo_solo VARCHAR2(30) NOT NULL,
    inclinacao_graus NUMBER(5,2) NOT NULL,
    distancia_agua_m NUMBER(8,2) NOT NULL,
    tipo_operacao VARCHAR2(40) NOT NULL,
    peso_equipamento_t NUMBER(5,2) NOT NULL,
    dias_desde_manutencao NUMBER NOT NULL,
    incidentes_previos NUMBER DEFAULT 0 NOT NULL,
    data_leitura TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_leitura_equipamento FOREIGN KEY (id_equipamento)
        REFERENCES equipamento(id_equipamento)
);

CREATE TABLE previsao_risco (
    id_previsao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_registro NUMBER NOT NULL,
    score_risco NUMBER(5,2) NOT NULL,
    nivel_risco VARCHAR2(20) NOT NULL,
    alerta VARCHAR2(255) NOT NULL,
    recomendacao VARCHAR2(255) NOT NULL,
    modelo_utilizado VARCHAR2(80) DEFAULT 'RandomForestClassifier' NOT NULL,
    data_previsao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_previsao_leitura FOREIGN KEY (id_registro)
        REFERENCES leitura_operacional(id_registro),
    CONSTRAINT chk_nivel_risco CHECK (nivel_risco IN ('baixo', 'medio', 'alto', 'critico')),
    CONSTRAINT chk_score_risco CHECK (score_risco BETWEEN 0 AND 100)
);

CREATE TABLE metrica_modelo (
    id_metrica NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_modelo VARCHAR2(80) NOT NULL,
    acuracia NUMBER(6,4) NOT NULL,
    erro_medio NUMBER(6,4),
    data_treinamento TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    observacao VARCHAR2(500)
);

-- 1. Quantidade de operações por nível de risco
SELECT nivel_risco, COUNT(*) AS total
FROM previsao_risco
GROUP BY nivel_risco
ORDER BY total DESC;

-- 2. Registros críticos com recomendação preventiva
SELECT l.id_registro, l.id_equipamento, l.regiao, l.tipo_operacao,
       p.score_risco, p.nivel_risco, p.alerta, p.recomendacao
FROM leitura_operacional l
JOIN previsao_risco p ON p.id_registro = l.id_registro
WHERE p.nivel_risco = 'critico'
ORDER BY p.score_risco DESC;

-- 3. Risco médio por região
SELECT l.regiao, ROUND(AVG(p.score_risco), 2) AS score_medio
FROM leitura_operacional l
JOIN previsao_risco p ON p.id_registro = l.id_registro
GROUP BY l.regiao
ORDER BY score_medio DESC;

-- 4. Fatores ambientais dos maiores riscos
SELECT l.id_registro, l.chuva_mm, l.umidade_solo, l.tipo_solo,
       l.inclinacao_graus, l.distancia_agua_m, p.score_risco, p.nivel_risco
FROM leitura_operacional l
JOIN previsao_risco p ON p.id_registro = l.id_registro
ORDER BY p.score_risco DESC
FETCH FIRST 10 ROWS ONLY;
